Repository prgrms-web-devcourse-final-project/WEB6_8_LuckyVicky_BE, pull requests merged in 2025-09, with the labels that each got.

#4 [feat] ServiceException 추가
  src/main/java/com/back/global/exception/ServiceException.java
Labels: feat

#13 Feat/12 고개용 대시보드 기능 구현 (테스트 Mock 구현)
  src/main/java/com/back/domain/dashboard/customer/controller/DashboardController.java
  src/main/java/com/back/domain/dashboard/customer/dto/response/AccountResponse.java
  src/main/java/com/back/domain/dashboard/customer/dto/response/ArtistApplicationResponse.java
  src/main/java/com/back/domain/dashboard/customer/dto/response/CashResponse.java
  src/main/java/com/back/domain/dashboard/customer/dto/response/FollowingResponse.java
  src/main/java/com/back/domain/dashboard/customer/dto/response/FundingResponse.java
  src/main/java/com/back/domain/dashboard/customer/dto/response/OrderResponse.java
  src/main/java/com/back/domain/dashboard/customer/dto/response/PageResponseDto.java
  src/main/java/com/back/domain/dashboard/customer/dto/response/ReturnResponse.java
  src/main/java/com/back/domain/dashboard/customer/dto/response/WishlistResponse.java
  src/main/java/com/back/domain/dashboard/customer/service/DashboardService.java
  src/main/java/com/back/domain/dashboard/customer/service/DashboardServiceImpl.java
  src/main/java/com/back/global/config/JpaConfig.java
  src/main/java/com/back/global/globalExceptionHandler/GlobalExceptionHandler.java
  src/main/java/com/back/global/rsData/RsData.java
  src/main/java/com/back/global/util/PageResponse.java
  src/test/java/com/back/BackApplicationTests.java
  src/test/java/com/back/config/TestConfig.java
  src/test/java/com/back/domain/dashboard/customer/controller/DashboardControllerTest.java
  src/test/java/com/back/domain/dashboard/customer/dto/response/AccountResponseTest.java
  src/test/java/com/back/domain/dashboard/customer/service/DashboardServiceImplTest.java
Labels: feat

#26 [feat] 펀딩 엔티티 구현
  src/main/java/com/back/domain/funding/entity/Funding.java
  src/main/java/com/back/domain/funding/entity/FundingCommunity.java
  src/main/java/com/back/domain/funding/entity/FundingContribution.java
  src/main/java/com/back/domain/funding/entity/FundingOption.java
  src/main/java/com/back/domain/funding/entity/FundingStatus.java
  src/main/java/com/back/domain/funding/entity/FundingUpdate.java
Labels: feat

#61 [feat] AuthService 구현
  src/main/java/com/back/domain/auth/dto/request/LoginRequest.java
  src/main/java/com/back/domain/auth/repository/UserTokenRepository.java
  src/main/java/com/back/domain/auth/service/AuthService.java
  src/main/java/com/back/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/back/domain/user/entity/Role.java
  src/main/java/com/back/domain/user/entity/User.java
  src/test/java/com/back/domain/auth/service/AuthServiceImplTest.java
Labels: feat

#66 [feat]장바구니 Service 구현
  src/main/java/com/back/domain/cart/dto/response/CartResponseDto.java
  src/main/java/com/back/domain/cart/entity/Cart.java
  src/main/java/com/back/domain/cart/repository/CartRepository.java
  src/main/java/com/back/domain/cart/service/CartService.java
  src/test/java/com/back/domain/cart/service/CartServiceTest.java
Labels: feat

#74 [refactor] 인증관련 코드 멘토님 피드백 반영
  src/main/java/com/back/domain/auth/controller/AuthController.java
  src/main/java/com/back/domain/auth/dto/request/LoginRequest.java
  src/main/java/com/back/domain/auth/dto/request/SignUpRequest.java
  src/main/java/com/back/domain/auth/entity/UserToken.java
  src/main/java/com/back/domain/auth/service/AuthService.java
  src/main/java/com/back/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/back/domain/user/entity/User.java
  src/main/java/com/back/global/util/IpUtils.java
  src/test/java/com/back/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/back/domain/auth/service/AuthServiceTest.java
Labels: refactor

#85 Feat/82 작가용 대시보드 정산내역 기능 구현
  src/main/java/com/back/domain/dashboard/artist/controller/ArtistDashboardController.java
  src/main/java/com/back/domain/dashboard/artist/dto/request/ArtistSettlementSearchRequest.java
  src/main/java/com/back/domain/dashboard/artist/dto/response/ArtistCancellationResponse.java
  src/main/java/com/back/domain/dashboard/artist/dto/response/ArtistExchangeResponse.java
  src/main/java/com/back/domain/dashboard/artist/dto/response/ArtistFundingResponse.java
  src/main/java/com/back/domain/dashboard/artist/dto/response/ArtistSettlementResponse.java
  src/main/java/com/back/domain/dashboard/artist/service/ArtistDashboardService.java
  src/main/java/com/back/domain/dashboard/artist/service/ArtistDashboardServiceImpl.java
  src/test/java/com/back/domain/dashboard/artist/controller/ArtistDashboardControllerTest.java
  src/test/java/com/back/domain/dashboard/artist/dto/response/ArtistFundingResponseTest.java
  src/test/java/com/back/domain/dashboard/artist/dto/response/ArtistSettlementResponseTest.java
  src/test/java/com/back/domain/dashboard/artist/service/ArtistDashboardServiceImplTest.java
Labels: feat

#92 [refactor] 검증 로직을 별도 Controller로 분리
  src/main/java/com/back/domain/auth/controller/ValidationController.java
  src/main/java/com/back/domain/auth/dto/request/ValidationCheckRequest.java
  src/main/java/com/back/domain/auth/dto/response/ValidationCheckResponse.java
  src/main/java/com/back/domain/auth/service/AuthService.java
  src/main/java/com/back/domain/auth/service/ValidationService.java
  src/main/java/com/back/domain/user/repository/UserRepository.java
  src/test/java/com/back/domain/auth/controller/ValidationControllerTest.java
  src/test/java/com/back/domain/auth/service/ValidationServiceTest.java
  src/test/java/com/back/domain/dashboard/customer/controller/DashboardControllerTest.java
Labels: refactor

#97 [feat] 작가 신청 엔티티 생성
  .env.default
  src/main/java/com/back/domain/artist/entity/ApplicationStatus.java
  src/main/java/com/back/domain/artist/entity/ArtistApplication.java
  src/main/java/com/back/domain/artist/entity/ArtistDocument.java
  src/main/java/com/back/domain/artist/entity/DocumentType.java
  src/main/java/com/back/global/security/config/SecurityConfig.java
Labels: feat

#109 [feat] OAuth2 의존성 및 설정 추가
  .env.default
  build.gradle.kts
  src/main/resources/application.yml
  src/test/java/com/back/domain/cart/controller/CartControllerTest.java
  src/test/java/com/back/domain/user/service/DevUserServiceTest.java
Labels: feat

#111 [feat] 펀딩 조회, 새소식 생성 구현
  src/main/java/com/back/domain/funding/controller/FundingController.java
  src/main/java/com/back/domain/funding/controller/FundingNewsController.java
  src/main/java/com/back/domain/funding/dto/request/FundingCommunityCreateRequest.java
  src/main/java/com/back/domain/funding/dto/request/FundingCreateRequest.java
  src/main/java/com/back/domain/funding/dto/request/FundingNewsCreateRequest.java
  src/main/java/com/back/domain/funding/dto/request/FundingUpdateRequest.java
  src/main/java/com/back/domain/funding/dto/response/FundingCardDto.java
  src/main/java/com/back/domain/funding/dto/response/FundingCommunityItemDto.java
  src/main/java/com/back/domain/funding/dto/response/FundingCreateResponse.java
  src/main/java/com/back/domain/funding/dto/response/FundingDetailResponse.java
  src/main/java/com/back/domain/funding/dto/response/FundingNewsItemDto.java
  src/main/java/com/back/domain/funding/entity/Funding.java
  src/main/java/com/back/domain/funding/entity/FundingCommunity.java
  src/main/java/com/back/domain/funding/entity/FundingContribution.java
  src/main/java/com/back/domain/funding/entity/FundingImage.java
  src/main/java/com/back/domain/funding/entity/FundingNews.java
  src/main/java/com/back/domain/funding/entity/FundingOption.java
  src/main/java/com/back/domain/funding/entity/FundingStatus.java
  src/main/java/com/back/domain/funding/repository/FundingCommunityRepository.java
  src/main/java/com/back/domain/funding/repository/FundingContributionRepository.java
  src/main/java/com/back/domain/funding/repository/FundingNewsRepository.java
  src/main/java/com/back/domain/funding/repository/FundingOptionRepository.java
  src/main/java/com/back/domain/funding/repository/FundingRepository.java
  src/main/java/com/back/domain/funding/service/FundingNewsService.java
  src/main/java/com/back/domain/funding/service/FundingService.java
  src/main/java/com/back/global/initData/TestInitData.java
  src/main/java/com/back/global/security/config/SecurityConfig.java
  src/test/java/com/back/domain/funding/controller/FundingControllerTest.java
Labels: feat

#117 [feat] DevInitData 생성
  src/main/generated/com/back/domain/order/order/entity/QOrder.java
  src/main/generated/com/back/domain/order/orderItem/entity/QOrderItem.java
  src/main/java/com/back/domain/user/entity/User.java
  src/main/java/com/back/global/initData/DevInitData.java
  src/main/java/com/back/global/security/config/SecurityConfig.java
Labels: feat

#120 [Refactor] Q클래스 원격에서 제거 + .gitignore 처리
  src/main/generated/com/back/domain/artist/entity/QArtistApplication.java
  src/main/generated/com/back/domain/artist/entity/QArtistDocument.java
  src/main/generated/com/back/domain/auth/entity/QUserToken.java
  src/main/generated/com/back/domain/cart/entity/QCart.java
  src/main/generated/com/back/domain/funding/entity/QFunding.java
  src/main/generated/com/back/domain/funding/entity/QFundingCommunity.java
  src/main/generated/com/back/domain/funding/entity/QFundingContribution.java
  src/main/generated/com/back/domain/funding/entity/QFundingImage.java
  src/main/generated/com/back/domain/funding/entity/QFundingNews.java
  src/main/generated/com/back/domain/funding/entity/QFundingOption.java
  src/main/generated/com/back/domain/order/order/entity/QOrder.java
  src/main/generated/com/back/domain/order/orderItem/entity/QOrderItem.java
  src/main/generated/com/back/domain/product/category/entity/QCategory.java
  src/main/generated/com/back/domain/product/product/entity/QAdditionalProduct.java
  src/main/generated/com/back/domain/product/product/entity/QOption.java
  src/main/generated/com/back/domain/product/product/entity/QProduct.java
  src/main/generated/com/back/domain/product/product/entity/QProductImage.java
  src/main/generated/com/back/domain/product/product/entity/QProductTagMapping.java
  src/main/generated/com/back/domain/product/tag/entity/QTag.java
  src/main/generated/com/back/domain/user/entity/QUser.java
  src/main/generated/com/back/global/jpa/entity/QBaseEntity.java
Labels: refactor

#122 [Refactor] .gitignore 추가
  .gitignore
Labels: refactor

#127 [fix] OAuth2 로그인 예외처리 및 방식 수정
  src/main/java/com/back/domain/user/entity/User.java
  src/main/java/com/back/global/security/oauth2/KakaoUserInfo.java
  src/main/java/com/back/global/security/oauth2/OAuth2SuccessHandler.java
  src/main/resources/application.yml
Labels: fix

#129 [feat] 주문 DTO 구현
  src/main/java/com/back/domain/cart/entity/Cart.java
  src/main/java/com/back/domain/order/order/dto/request/OrderCancelRequestDto.java
  src/main/java/com/back/domain/order/order/dto/request/OrderExchangeRequestDto.java
  src/main/java/com/back/domain/order/order/dto/request/OrderRefundRequestDto.java
  src/main/java/com/back/domain/order/order/dto/request/OrderRequestDto.java
  src/main/java/com/back/domain/order/order/dto/request/OrderStatusChangeRequestDto.java
  src/main/java/com/back/domain/order/order/dto/response/OrderListResponseDto.java
  src/main/java/com/back/domain/order/order/dto/response/OrderResponseDto.java
Labels: feat

#139 [feat] 펀딩 상태 변경 구현 및 스케줄러 추가
  src/main/java/com/back/BackApplication.java
  src/main/java/com/back/domain/funding/controller/FundingStatusController.java
  src/main/java/com/back/domain/funding/entity/Funding.java
  src/main/java/com/back/domain/funding/repository/FundingRepository.java
  src/main/java/com/back/domain/funding/scheduler/FundingStatusScheduler.java
  src/main/java/com/back/domain/funding/service/FundingStatusService.java
  src/main/java/com/back/global/initData/TestInitData.java
  src/main/resources/application.yml
  src/test/java/com/back/domain/funding/controller/FundingControllerTest.java
  src/test/java/com/back/domain/funding/controller/FundingStatusControllerTest.java
Labels: feat
