Repository prgrms-web-devcourse-final-project/WEB6_8_LuckyVicky_BE, pull requests merged in 2025-10, with the labels that each got.

#145 [feat] 작가 신청 로직 구현 및 리팩토링
  src/main/java/com/back/domain/artist/dto/request/ArtistApplicationReviewRequest.java
  src/main/java/com/back/domain/artist/dto/response/ArtistApplicationSimpleResponse.java
  src/main/java/com/back/domain/artist/service/ArtistApplicationAdminService.java
  src/main/java/com/back/domain/artist/service/ArtistApplicationService.java
  src/main/java/com/back/domain/user/entity/Grade.java
  src/main/java/com/back/domain/user/entity/User.java
  src/main/java/com/back/domain/user/service/UserService.java
  src/main/java/com/back/domain/user/user/DevUserService.java
  src/main/java/com/back/global/initData/DevInitData.java
  src/main/java/com/back/global/initData/TestInitData.java
  src/test/java/com/back/domain/artist/service/ArtistApplicationAdminServiceTest.java
  src/test/java/com/back/domain/artist/service/ArtistApplicationServiceTest.java
  src/test/java/com/back/domain/dashboard/customer/service/DashboardServiceImplTest.java
  src/test/java/com/back/domain/user/service/DevUserServiceTest.java
  src/test/java/com/back/domain/user/service/UserServiceTest.java
Labels: feat

#152 [feat] 펀딩 목록 조회 구현
  src/main/java/com/back/domain/funding/controller/FundingController.java
  src/main/java/com/back/domain/funding/repository/FundingCustomRepository.java
  src/main/java/com/back/domain/funding/repository/FundingCustomRepositoryImpl.java
  src/main/java/com/back/domain/funding/repository/FundingRepository.java
  src/main/java/com/back/domain/funding/service/FundingService.java
  src/main/java/com/back/global/initData/TestInitData.java
  src/test/java/com/back/domain/funding/controller/FundingControllerTest.java
Labels: feat

#155 [refactor] 상품 식별 번호(uuid) 추가
  src/main/generated/com/back/domain/order/orderItem/entity/QOrderItem.java
  src/main/java/com/back/domain/product/product/controller/ProductController.java
  src/main/java/com/back/domain/product/product/dto/response/ProductListResponse.java
  src/main/java/com/back/domain/product/product/entity/Product.java
  src/main/java/com/back/domain/product/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/back/domain/product/product/repository/ProductRepository.java
  src/main/java/com/back/domain/product/product/service/ProductService.java
  src/main/java/com/back/global/exception/ServiceException.java
  src/main/java/com/back/global/s3/S3Service.java
  src/main/java/com/back/global/s3/S3ValidationService.java
  src/test/java/com/back/domain/product/product/controller/ProductControllerTest.java
  src/test/java/com/back/global/s3/S3ServiceTest.java
Labels: refactor

#157 Feat/154 사용자 유입 경로 기능구현
  .gitignore
  build.gradle.kts
  src/main/java/com/back/domain/dashboard/admin/controller/AdminDashboardController.java
  src/main/java/com/back/domain/dashboard/admin/dto/response/AdminOverviewResponse.java
  src/main/java/com/back/domain/dashboard/admin/dto/response/AdminTrafficSourceResponse.java
  src/main/java/com/back/domain/dashboard/admin/service/AdminDashboardService.java
  src/main/java/com/back/domain/dashboard/admin/service/AdminDashboardServiceImpl.java
  src/main/java/com/back/domain/dashboard/admin/service/GA4AnalyticsService.java
  src/main/java/com/back/domain/dashboard/artist/controller/ArtistDashboardController.java
  src/main/java/com/back/domain/dashboard/artist/dto/response/ArtistMainResponse.java
  src/main/java/com/back/domain/dashboard/artist/dto/response/ArtistTrafficSourceResponse.java
  src/main/java/com/back/domain/dashboard/artist/service/ArtistDashboardService.java
  src/main/java/com/back/domain/dashboard/artist/service/ArtistDashboardServiceImpl.java
  src/main/java/com/back/domain/product/product/controller/ProductController.java
  src/main/java/com/back/domain/product/product/dto/response/ShareLinkResponse.java
  src/main/java/com/back/domain/product/product/entity/Product.java
  src/main/java/com/back/domain/product/product/repository/ProductRepository.java
  src/main/java/com/back/domain/product/product/service/ProductService.java
  src/main/java/com/back/global/config/GoogleAnalyticsConfig.java
  src/main/resources/application.yml
  src/test/java/com/back/domain/dashboard/artist/dto/response/ArtistMainResponseTest.java
Labels: feat

#163 Refactor/158 대시보드 jwt 설정
  src/main/java/com/back/domain/dashboard/admin/controller/AdminDashboardController.java
  src/main/java/com/back/domain/dashboard/admin/dto/response/AdminArtistApplicationDetailResponse.java
  src/main/java/com/back/domain/dashboard/admin/dto/response/AdminFundingResponse.java
  src/main/java/com/back/domain/dashboard/admin/service/AdminDashboardService.java
  src/main/java/com/back/domain/dashboard/admin/service/AdminDashboardServiceImpl.java
  src/main/java/com/back/domain/dashboard/artist/controller/ArtistDashboardController.java
  src/main/java/com/back/domain/dashboard/artist/service/ArtistDashboardService.java
  src/main/java/com/back/domain/dashboard/artist/service/ArtistDashboardServiceImpl.java
  src/main/java/com/back/domain/dashboard/customer/controller/DashboardController.java
  src/main/java/com/back/domain/dashboard/customer/service/DashboardService.java
  src/main/java/com/back/domain/dashboard/customer/service/DashboardServiceImpl.java
  src/test/java/com/back/domain/dashboard/admin/controller/AdminDashboardControllerTest.java
  src/test/java/com/back/domain/dashboard/admin/service/AdminDashboardServiceImplTest.java
  src/test/java/com/back/domain/dashboard/artist/controller/ArtistDashboardControllerTest.java
  src/test/java/com/back/domain/dashboard/artist/service/ArtistDashboardServiceImplTest.java
  src/test/java/com/back/domain/dashboard/customer/controller/DashboardControllerTest.java
  src/test/java/com/back/domain/dashboard/customer/service/DashboardServiceImplTest.java
Labels: refactor

#168 [refactor] deploy.yml 수정
  .github/workflows/deploy.yml
Labels: refactor

#174 [refactor] deploy.yml에 주석 추가(의미x)
  .github/workflows/deploy.yml
Labels: refactor

#185 [feat] 주문 취소/교환/환불 엔티티 및 OrderStatus enum 구현
  src/main/java/com/back/domain/order/exchange/entity/Exchange.java
  src/main/java/com/back/domain/order/exchange/entity/ExchangeItem.java
  src/main/java/com/back/domain/order/order/entity/Order.java
  src/main/java/com/back/domain/order/order/entity/OrderStatus.java
  src/main/java/com/back/domain/order/refund/entity/Refund.java
  src/main/java/com/back/domain/order/refund/entity/RefundItem.java
Labels: feat

#203 feat/164 creatAt이었던 부분이 creatDate를 참조해야되는 문제 해결
  src/main/java/com/back/domain/order/exchange/repository/ExchangeRepository.java
  src/main/java/com/back/domain/order/refund/repository/RefundRepository.java
Labels: feat

#210 [fix] Set-Cookie 헤더 설정 방식 개선
  src/main/java/com/back/domain/auth/controller/AuthController.java
Labels: fix

#217 [feat] 주문 취소/교환/환불 Service 로직 구현
  src/main/java/com/back/domain/order/common/service/BaseOrderActionService.java
  src/main/java/com/back/domain/order/exchange/entity/Exchange.java
  src/main/java/com/back/domain/order/exchange/repository/ExchangeRepository.java
  src/main/java/com/back/domain/order/exchange/service/ExchangeService.java
  src/main/java/com/back/domain/order/exchange/util/ExchangeConverter.java
  src/main/java/com/back/domain/order/order/entity/Order.java
  src/main/java/com/back/domain/order/refund/entity/Refund.java
  src/main/java/com/back/domain/order/refund/repository/RefundRepository.java
  src/main/java/com/back/domain/order/refund/service/RefundService.java
  src/main/java/com/back/domain/order/refund/util/RefundConverter.java
  src/test/java/com/back/domain/order/common/service/BaseOrderActionServiceTest.java
  src/test/java/com/back/domain/order/exchange/service/ExchangeServiceTest.java
  src/test/java/com/back/domain/order/refund/service/RefundServiceTest.java
Labels: feat

#226 [Feat] 카테고리 조회,등록,수정,삭제
  src/main/java/com/back/domain/product/category/controller/CategoryController.java
  src/main/java/com/back/domain/product/category/dto/request/CategoryRequest.java
  src/main/java/com/back/domain/product/category/dto/response/CategoryResponse.java
  src/main/java/com/back/domain/product/category/entity/Category.java
  src/main/java/com/back/domain/product/category/repository/CategoryRepository.java
  src/main/java/com/back/domain/product/category/service/CategoryService.java
  src/main/java/com/back/domain/product/product/repository/ProductRepository.java
  src/main/java/com/back/global/security/config/SecurityConfig.java
Labels: feat

#225 [fix] 로그아웃 프론트 500에러 수정
  src/main/java/com/back/domain/auth/controller/AuthController.java
  src/test/java/com/back/domain/auth/controller/AuthControllerTest.java
Labels: fix

#231 Refactor/227 대쉬보드 실제 db연동
  src/main/java/com/back/domain/dashboard/admin/service/AdminDashboardServiceImpl.java
  src/main/java/com/back/domain/dashboard/artist/dto/DailyTrendDto.java
  src/main/java/com/back/domain/dashboard/artist/dto/DashboardStatsDto.java
  src/main/java/com/back/domain/dashboard/artist/service/ArtistDashboardService.java
  src/main/java/com/back/domain/dashboard/artist/service/ArtistDashboardServiceImpl.java
  src/main/java/com/back/domain/order/order/repository/OrderRepository.java
  src/main/java/com/back/domain/product/product/repository/ProductRepository.java
  src/test/java/com/back/domain/dashboard/artist/service/ArtistDashboardServiceImplTest.java
Labels: refactor

#241 [fix] 소셜 로그인, 중복인증 버그 수정
  src/main/java/com/back/domain/auth/service/AuthService.java
  src/main/java/com/back/global/security/config/SecurityConfig.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: fix

#245 [feat] 작가 공개 정보 조회 API 구현
  src/main/java/com/back/domain/artist/controller/ArtistController.java
  src/main/java/com/back/domain/artist/dto/response/ArtistListResponse.java
  src/main/java/com/back/domain/artist/dto/response/ArtistProductResponse.java
  src/main/java/com/back/domain/artist/dto/response/ArtistPublicProfileResponse.java
  src/main/java/com/back/domain/artist/repository/ArtistProfileRepository.java
  src/main/java/com/back/domain/artist/service/ArtistPublicService.java
  src/main/java/com/back/domain/product/product/repository/ProductRepository.java
  src/main/java/com/back/global/security/config/SecurityConfig.java
  src/test/java/com/back/domain/artist/controller/ArtistControllerTest.java
  src/test/java/com/back/domain/auth/service/AuthServiceTest.java
Labels: feat

#246 Refactor/239 교환/환불 신청 모달 상품 정보 조회 실제 db 연동
  src/main/java/com/back/domain/dashboard/customer/controller/DashboardController.java
  src/main/java/com/back/domain/dashboard/customer/service/DashboardService.java
  src/main/java/com/back/domain/dashboard/customer/service/DashboardServiceImpl.java
  src/test/java/com/back/domain/dashboard/customer/service/DashboardServiceImplTest.java
Labels: refactor

#249 [feat] 결제 dto 구현 및 재고 관리 로직 추가
  src/main/java/com/back/domain/order/exchange/dto/request/ExchangeRequestDto.java
  src/main/java/com/back/domain/order/exchange/entity/Exchange.java
  src/main/java/com/back/domain/order/exchange/entity/ExchangeReasonType.java
  src/main/java/com/back/domain/order/exchange/service/ExchangeService.java
  src/main/java/com/back/domain/order/order/service/OrderService.java
  src/main/java/com/back/domain/order/refund/dto/request/RefundRequestDto.java
  src/main/java/com/back/domain/order/refund/entity/Refund.java
  src/main/java/com/back/domain/order/refund/entity/RefundReasonType.java
  src/main/java/com/back/domain/order/refund/service/RefundService.java
  src/main/java/com/back/domain/payment/cash/dto/request/CashChargeRequestDto.java
  src/main/java/com/back/domain/payment/cash/dto/request/CashExchangeRequestDto.java
  src/main/java/com/back/domain/payment/cash/dto/response/CashChargeResponseDto.java
  src/main/java/com/back/domain/payment/cash/dto/response/CashExchangeResponseDto.java
  src/main/java/com/back/domain/payment/cash/dto/response/CashTransactionResponseDto.java
  src/main/java/com/back/domain/payment/moriCash/dto/request/MoriCashPaymentRequestDto.java
  src/main/java/com/back/domain/payment/moriCash/dto/request/MoriCashRefundRequestDto.java
  src/main/java/com/back/domain/payment/moriCash/dto/response/MoriCashBalanceResponseDto.java
  src/main/java/com/back/domain/payment/moriCash/dto/response/MoriCashPaymentResponseDto.java
  src/main/java/com/back/domain/payment/moriCash/dto/response/MoriCashRefundResponseDto.java
  src/main/java/com/back/domain/payment/moriCash/entity/MoriCashRecharge.java
  src/main/java/com/back/domain/payment/moriCash/entity/MoriCashRechargeStatus.java
  src/main/java/com/back/domain/payment/moriCash/repository/MoriCashRechargeRepository.java
Labels: feat
